name: "LFTP Worker"
version: "1.1.6"
slug: "lftp_worker"
description: "Motore LFTP universale per trasferimenti tramite comandi stdin"
startup: "services"
boot: "manual"
stdin: true
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
init: false
options:
  host: "indirizzo.server.ftp"
  username: "username"
  password: "password"
schema:
  host: str
  username: str
  password: password
map:
  - config:rw
  - share:rw
  - media:rw
